/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_unit_testing;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testHelloYourName() {
        Library classUnderTest = new Library();
        assertEquals(
                "Hello Tyler!",
                classUnderTest.greeting("Tyler")
        );
    }
}
